export default function() {
  return {
    fccleaderboard: {
      title: 'FCC Leaderboard',
      description: 'View the the top 100 FreeCodeCamp contributors. View the top scorers of all time or in the past 30 days',
      image: require('../resources/img/project/fcc-leaderboard-min.png'),
      builtwith: 'React, Redux, Emotion.js',
      github: 'https://nimaiwalsh.github.io/fcc-leaderboard/',
      githsrc: 'https://github.com/nimaiwalsh/fcc-leaderboard',
    },
    markdownpreview: {
      title: 'Markdown Previewer',
      description: 'Input your Markdown code (Same as GitHub) and preview the HTML output.',
      image: require('../resources/img/project/markdown-previewer-min.png'),
      builtwith: 'React',
      github: 'https://nimaiwalsh.github.io/markdown-previewer/',
      githsrc: 'https://github.com/nimaiwalsh/markdown-previewer',
    },
    weatherapp: {
      title: 'WeatherApp',
      description: 'A simple weather app that uses a search or geolocation to find the local weather',
      image: require('../resources/img/project/weather-app-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript',
      github: 'https://nimaiwalsh.github.io/WeatherApp/',
      githsrc: 'https://github.com/nimaiwalsh/WeatherApp',
    },
    jscalculator: {
      title: 'JS Calculator',
      description: 'Basic calculator built with vanilla JS and CSS',
      image: require('../resources/img/project/js-calculator-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript',
      github: 'https://nimaiwalsh.github.io/JavaScriptCalculator/',
      githsrc: 'https://github.com/nimaiwalsh/JavaScriptCalculator',
    },
    twitchviewer: {
      title: 'Twitch Viewer',
      description: 'An app that displays a list of Twitch users and streaming status',
      image: require('../resources/img/project/twitch-viewer-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript, Webpack, Babel',
      github: 'https://nimaiwalsh.github.io/twitchAPI/',
      githsrc: 'https://github.com/nimaiwalsh/twitchAPI',
    },
    wikisearch: {
      title: 'Wiki Search',
      description: 'A basic search app that uses the Wiki API to provide answers',
      image: require('../resources/img/project/wiki-viewer-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript',
      github: 'https://nimaiwalsh.github.io/wikiViewer/',
      githsrc: 'https://github.com/nimaiwalsh/wikiViewer',
    },
    tactactoe: {
      title: 'Tac Tac Toe',
      description: 'A Tic Tac Toe game. It has 1 player and 2 player mode and stores/displays the history of all player moves.',
      image: require('../resources/img/project/tic-tac-toe-min.jpeg'),
      builtwith: 'HTML, CSS, React',
      github: 'https://nimaiwalsh.github.io/TicTacToe/',
      githsrc: 'https://github.com/nimaiwalsh/TicTacToe',
    },
    simongame: {
      title: 'Retro Simon Game',
      description: 'The Classic Retro Simon Game. Follow Simo\'s 20 moves to win the game.',
      image: require('../resources/img/project/simon-says-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript - React',
      github: 'https://nimaiwalsh.github.io/simon-game/',
      githsrc: 'https://github.com/nimaiwalsh/simon-game',
    },
    pomodoraclock: {
      title: 'Pomodora Clock',
      description: 'Set your work and break times and be notified when to take a break',
      image: require('../resources/img/project/pomodora-clock-min.jpeg'),
      builtwith: 'HTML, CSS, JavaScript - React',
      github: 'https://nimaiwalsh.github.io/Pomodora-Clock/',
      githsrc: 'https://github.com/nimaiwalsh/Pomodora-Clock',
    },
    weatherforcaster: {
      title: 'Weather Forcaster',
      description: 'Search for your city and add multiple cities to a list. The list contains a chart for Temp, Humidity and Air Pressure every 3 hours for 5 days.',
      image: require('../resources/img/project/weather-forecast-react-min.jpeg'),
      builtwith: 'HTML, CSS, React, Redux',
      github: 'https://nimaiwalsh.github.io/weather-app-react-redux/',
      githsrc: 'https://github.com/nimaiwalsh/weather-app-react-redux',
    }
  }
}